name: VoIPmonitor CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Remove conflicting packages
      run: |
        sudo apt-get remove -y containerd containerd.io
        sudo apt-get autoremove -y

    - name: Clean up and update
      run: |
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*
        sudo apt-get update

    - name: Fix broken dependencies
      run: sudo apt-get install -f

    - name: Upgrade installed packages
      run: sudo apt-get upgrade -y

    - name: Reconfigure packages
      run: sudo dpkg --configure -a

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Start MySQL Docker Container
      run: |
        sudo docker run --name mysql -e MYSQL_ROOT_PASSWORD=rootpassword -e MYSQL_DATABASE=voipmonitor -e MYSQL_USER=voipuser -e MYSQL_PASSWORD=voippassword -p 3306:3306 -d mysql:8.0

    - name: Wait for MySQL to be ready
      run: |
        for i in {1..30}; do
          if sudo docker exec mysql mysqladmin ping -h"localhost" --silent; then
            echo "MySQL is up and running!"
            break
          else
            echo "Waiting for MySQL..."
            sleep 5
          fi
        done

    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libpcap-dev libmysqlclient-dev libcurl4-openssl-dev libssl-dev

    - name: Build VoIPmonitor
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        cd build
        make test

    - name: Run VoIPmonitor
      run: |
        sudo mkdir -p /etc/voipmonitor
        echo -e "user=root\npassword=rootpassword\nhost=localhost\ndatabase=voipmonitor" | sudo tee /etc/voipmonitor.conf
        sudo build/voipmonitor --config-file /etc/voipmonitor.conf --pidfile /var/run/voipmonitor.pid --daemon

    - name: Verify VoIPmonitor is running
      run: |
        ps aux | grep voipmonitor
        sudo netstat -tuln | grep 5029  # Adjust this port if necessary

