name: VoIPmonitor CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libpcap-dev libmysqlclient-dev libcurl4-openssl-dev libssl-dev mysql-server

    - name: Initialize MySQL
      run: |
        sudo systemctl stop mysql
        sudo mysqld --initialize-insecure --user=mysql
        sudo systemctl start mysql
        sudo mysql --execute="ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'rootpassword';"
        sudo mysql --execute="CREATE DATABASE IF NOT EXISTS voipmonitor;"
        sudo mysql --execute="CREATE USER 'voipuser'@'localhost' IDENTIFIED BY 'voippassword';"
        sudo mysql --execute="GRANT ALL PRIVILEGES ON voipmonitor.* TO 'voipuser'@'localhost';"
        sudo mysql --execute="FLUSH PRIVILEGES;"

    - name: Build VoIPmonitor
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        cd build
        make test

    - name: Run VoIPmonitor
      run: |
        sudo mkdir -p /etc/voipmonitor
        echo -e "user=root\npassword=rootpassword\nhost=localhost\ndatabase=voipmonitor" | sudo tee /etc/voipmonitor.conf
        sudo build/voipmonitor --config-file /etc/voipmonitor.conf --pidfile /var/run/voipmonitor.pid --daemon

    - name: Verify VoIPmonitor is running
      run: |
        ps aux | grep voipmonitor
        sudo netstat -tuln | grep 5029  # Adjust this port if necessary
