name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libmysqlclient-dev \
          cmake \
          make \
          g++ \
          pkg-config \
          libpcap-dev \
          libvorbis-dev \
          libsnappy-dev \
          libfftw3-dev \
          libjson-c-dev \
          libcurl4-openssl-dev \
          librrd-dev \
          liblzo2-dev \
          libxml2-dev \
          libglib2.0-dev \
          zlib1g-dev \
          liblzma-dev

    - name: Run configure
      run: |
        if [ -f ./configure ]; then
          ./configure
        fi

    - name: Build and install
      run: |
        make clean
        make -j$(nproc)
        sudo make install

    - name: Run tests
      run: |
        if [ -f ./test ]; then
          ./test
        fi
